from datetime import UTC, datetime, timedelta

import pytest
from database.enums import ShipmentDirection, ShipmentStatus
from database.models import Shipment
from fastapi.testclient import TestClient
from sqlalchemy.orm import Session


@pytest.mark.integration
def test_shipments_delay_summary_temporal_logic(
    client: TestClient, db_session: Session, seed_base_world: dict
) -> None:
    """
    Validates the time-series logic of the delay summary tool.

    Scenario (Threshold is 48 hours):
    1. On-Time Delivered: Transit time 18h.
    2. Delayed Delivered: Transit time 58h. (Should flag as delayed)
    3. On-Time In-Transit: Shipped 10h ago.
    4. Delayed In-Transit: Shipped 50h ago. (Should flag as delayed)
    """
    # 1. Arrange
    wh = seed_base_world["warehouse"]
    now = datetime.now(UTC)

    # Shipment 1: On-time and delivered (18 hours transit)
    s1 = Shipment(
        direction=ShipmentDirection.INBOUND,
        status=ShipmentStatus.DELIVERED,
        destination_warehouse_id=wh.id,
        shipped_at=now - timedelta(hours=20),
        arrived_at=now - timedelta(hours=2),
    )

    # Shipment 2: Delivered but took too long (58 hours transit)
    s2 = Shipment(
        direction=ShipmentDirection.INBOUND,
        status=ShipmentStatus.DELIVERED,
        destination_warehouse_id=wh.id,
        shipped_at=now - timedelta(hours=60),
        arrived_at=now - timedelta(hours=2),
    )

    # Shipment 3: Still in transit, but recently shipped (10 hours ago -> Not delayed)
    s3 = Shipment(
        direction=ShipmentDirection.INBOUND,
        status=ShipmentStatus.IN_TRANSIT,
        destination_warehouse_id=wh.id,
        shipped_at=now - timedelta(hours=10),
        arrived_at=None,
    )

    # Shipment 4: Still in transit, shipped a long time ago (50 hours ago -> Delayed)
    s4 = Shipment(
        direction=ShipmentDirection.INBOUND,
        status=ShipmentStatus.IN_TRANSIT,
        destination_warehouse_id=wh.id,
        shipped_at=now - timedelta(hours=50),
        arrived_at=None,
    )

    db_session.add_all([s1, s2, s3, s4])
    db_session.flush()

    # 2. Act
    # Query for all shipments shipped in the last 100 hours
    response = client.get(
        "/api/v1/smart-query/shipments/delay-summary",
        params={
            "date_from": (now - timedelta(hours=100)).isoformat(),
            "date_to": (now + timedelta(hours=1)).isoformat(),
            "warehouse_id": str(wh.id),
        },
    )

    # 3. Assert
    assert response.status_code == 200
    data = response.json()["data"]

    # Verify Global KPI Aggregations
    assert data["total_shipments"] == 4
    assert data["delivered_count"] == 2
    assert data["in_transit_count"] == 2
    assert data["delayed_count"] == 2  # s2 and s4

    # Verify Average Transit Time Math: (18h + 58h) / 2 = 38.0h
    # Notice it entirely ignores the in-transit items for this calculation
    assert data["avg_transit_hours"] == 38.0

    # Verify Delayed Shipments Detail List
    delayed_list = data["delayed_shipments"]
    assert len(delayed_list) == 2

    delayed_ids = [d["shipment_id"] for d in delayed_list]
    assert str(s2.id) in delayed_ids
    assert str(s4.id) in delayed_ids

    # Verify the reason strings generated by the SQL CASE statements
    s2_detail = next(d for d in delayed_list if d["shipment_id"] == str(s2.id))
    s4_detail = next(d for d in delayed_list if d["shipment_id"] == str(s4.id))

    assert "Transit exceeded" in s2_detail["delayed_reason"]
    assert "In transit over" in s4_detail["delayed_reason"]
