"""unique_constraint_production_location_inventar_balance

Revision ID: 6b021e7f25d2
Revises: 0001_initial_schema
Create Date: 2026-03-24 21:15:16.774605
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002_unique_constraint_production_location_inventar_balance'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_inventory_balance_product_location', 'inventory_balances', ['product_id', 'location_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_inventory_balance_product_location', 'inventory_balances', type_='unique')
    # ### end Alembic commands ###
